version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:Beczka0106@host.docker.internal:5432/mystery_night_planner
      - JWT_SECRET=Beczka0106

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend